# Use postgres/example user/password credentials
version: '3.6'

services:
    db:
        image: postgres:9.6
        hostname: 'localhost'
        container_name: 'postgres'
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=123456
        ports:
            - '5432:5432'
